openapi: 3.0.0
info:
  title: Mon API
  version: 1.0.0
servers:
  - url: http://localhost:3001
paths:
  /boats:
    get:
      summary: Obtenir tous les bateaux
      tags:
        - Boat
      responses:
        '200':
          description: Liste des bateaux
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Boat'
              example:
                - id: "uuid-1"
                  name: "Black Pearl"
                  goldCargo: 50000
                  created_at: "2023-10-19T00:00:00.000Z"
                  captain: "Jack Sparrow"
                  status: "sailing"
                  crewSize: 50
                  created_by: "user-uuid-1"
                  last_modified: "2023-10-19T00:00:00.000Z"
                - id: "uuid-2"
                  name: "Queen Anne's Revenge"
                  goldCargo: 10000
                  created_at: "2023-10-20T00:00:00.000Z"
                  captain: "Blackbeard"
                  status: "docked"
                  crewSize: 80
                  created_by: "user-uuid-2"
                  last_modified: "2023-10-20T00:00:00.000Z"

  /boat:
    post:
      summary: Créer un nouveau bateau
      tags:
        - Boat
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoatRequest'
            example:
              name: "Flying Dutchman"
              goldCargo: 75000
              captain: "Davy Jones"
              status: "docked"
              crewSize: 150
              createdBy: "user-uuid-3"
      responses:
        '201':
          description: Bateau créé avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Boat'
        '400':
          description: Mauvaise requête

  /boat/{id}:
    delete:
      summary: Supprimer un bateau par son ID
      tags:
        - Boat
      parameters:
        - name: id
          in: path
          description: ID du bateau à supprimer (UUID)
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Bateau supprimé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Boat deleted successfully
        '404':
          description: Bateau non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Boat not found

    patch:
      summary: Modifier un bateau par son ID
      tags:
        - Boat
      parameters:
        - name: id
          in: path
          required: true
          description: ID du bateau à modifier (UUID)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoatRequestUpdate'
            example:
              name: "deded"
              goldCargo: 88000
              captain: "Edward Teach"
              crewSize: 120
      responses:
        '200':
          description: Bateau modifié avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Boat'
        '400':
          description: Mauvaise requête
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid input data
        '404':
          description: Bateau non trouvé
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Boat not found
  /auth:
    post:
      summary: Connexion utilisateur (login)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
            example:
              username: "root"
              password: "root"
      responses:
        '200':
          description: Connexion réussie, retourne un token JWT
        '401':
          description: Authentification échouée (mauvais identifiants)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid username or password
  /register:
    post:
      summary: Connexion utilisateur (register Créer compte)
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDTO'
            example:
              username: "root"
              password: "root"
      responses:
        '200':
          description: Connexion réussie, retourne un token JWT
        '401':
          description: Authentification échouée (mauvais identifiants)
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Invalid username or password 
  /me:
    get:
     tags:
      - Auth
     summary: Get the connected user
     description: |
      Returns information about the currently authenticated user.
     operationId: getUserConnected
     security:
      - cookieAuth: [] 
     responses:
      '200':
        description: Authenticated user returned
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user
      '401':
        description: User not authenticated or token missing
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
                  example: User not authenticated
         
  /sailToPort/{destination}:
    post:
      summary: Naviguer vers un autre port
      description: Valide un port de destination et envoie le bateau vers ce port.
      tags:
        - Boat
      parameters:
        - name: destination
          in: path
          required: true
          description: Nom ou identifiant du port de destination
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoatRequest'
            example:
              name: "hamza "
              goldCargo: 75000
              createdAt: "2025-09-13T12:00:00.000Z"
              captain: "Davy Jones"
              status: "sailing"
              crewSize: 150
              createdBy: "user-uuid-3"

      responses:
        '200':
          description: Bateau envoyé avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Boat sent to destination successfully
        '400':
          description: Port invalide
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Port invalide.
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Erreur pendant la navigation du bateau.
  /getAvailablePorts:
    get:
      summary: Obtenir les ports disponibles
      description: Récupère la liste des ports disponibles via le broker.
      tags:
        - Boat
      responses:
        '200':
          description: Liste des ports disponibles récupérée avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  ports:
                    type: array
                    items:
                      type: string
                example:
                  ports:
                    - Tortuga
                    - Port Royal
                    - Nassau
        '500':
          description: Erreur interne du serveur
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Erreur serveur : impossible de récupérer les ports disponibles.
  /ship/dock:
    post:
      summary: Dock un bateau sur le port (via le broker)
      description: Vérifie l’identité du broker via les headers et dock un bateau si le port n’est pas plein.
      tags:
        - Boat
      parameters:
        - name: app-token
          in: header
          required: true
          schema:
            type: string
          description: Jeton d'authentification du broker
        - name: client-id
          in: header
          required: true
          schema:
            type: string
          description: Identifiant du client du broker
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BoatRequest'
            example:
              name: "Flying Dutchman"
              goldCargo: 75000
              captain: "Davy Jones"
              status: "docked"
              crewSize: 150
              created_by: "user-uuid-3"
              created_at: "2025-09-13T12:00:00.000Z"
              last_modified: "2025-09-13T12:00:00.000Z"
      responses:
        '201':
          description: Bateau docké avec succès
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Bateau docké avec succès.
                  boat:
                    $ref: '#/components/schemas/Boat'
        '400':
          description: Port plein
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Port plein. Impossible de dock un nouveau bateau.
        '401':
          description: Headers manquants
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: App-Token ou Client-Id manquant.
        '403':
          description: Accès interdit
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Accès interdit : token ou ID invalide.
        '500':
          description: Erreur interne
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Erreur serveur inconnue.
components:
  schemas:
    Boat:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        goldCargo:
          type: integer
          minimum: 0
          maximum: 1000000
        created_at:
          type: string
          format: date-time
        captain:
          type: string
        status:
          type: string
          enum:
            - docked
            - sailing
            - lookingForAFight
        crewSize:
          type: integer
          minimum: 1
          maximum: 500
        created_by:
          type: string
          format: uuid
        last_modified:
          type: string
          format: date-time

    BoatRequest:
      type: object
      required:
        - name
        - goldCargo
        - captain
        - status
        - crewSize
        - created_by
      properties:
        name:
          type: string
        goldCargo:
          type: integer
          minimum: 0
          maximum: 1000000
        captain:
          type: string
        status:
          type: string
          enum:
            - docked
            - sailing
            - lookingForAFight
        crewSize:
          type: integer
          minimum: 1
          maximum: 500
        created_by:
          type: string
          format: uuid

    BoatRequestUpdate:
      type: object
      properties:
        name:
          type: string
        goldCargo:
          type: integer
          minimum: 0
          maximum: 1000000
        captain:
          type: string
        crewSize:
          type: integer
          minimum: 1
          maximum: 500
    UserDTO:
      type: object
      required:
        - userName
        - password
      properties:
        id:
          type: string
          format: uuid
        userName:
          type: string
        password:
          type: string
    securitySchemes:
      cookieAuth:
        type: apiKey
        in: cookie
        name: token 